
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//:slang": ' '.join([
            '--host_features=-compiler_param_file',
            '--host_features=-layering_check',
            '--host_features=-parse_headers',
            '--features=-compiler_param_file',
            '--features=-layering_check',
            '--features=-parse_headers',
        ])
    },

    # '--host_features=-compiler_param_file', '--host_features=-layering_check', '--host_features=-parse_headers'
)
